export const CARICATURES = {
  barbarian:  {
    key: 'barbarian',
    name: "Barbarian",
    desc: "The Barbarian is the greatest warrior of all. But beware of magic for your sword is no defense against it.",
    attack: 3,
    defense: 2,
    move: 2,
    mind: 2,
    body: 8,
  },
  dwarf: {
    key: 'dwarf',
    name: "Dwarf",
    desc: "The Dwarf is a good warrior and can always disarm traps that you find. You may remove any visible trap in the same room or passage.",
    attack: 2,
    defense: 2,
    move: 2,
    mind: 3,
    body: 7,
  },
  wizard: {
    key: 'wizard',
    name: "Wizard",
    desc: "The Wizard has many spells that can aid you. However, in combat you are weak, so use your spells well and avoid combat.",
    attack: 1,
    defense: 2,
    move: 2,
    mind: 6,
    body: 4,
  },
  elf: {
    key: 'elf',
    name: "Elf",
    desc: "The Elf is a master of both magic and the sword. You must use both well if you are to triumph.",
    attack: 2,
    defense: 2,
    move: 2,
    mind: 4,
    body: 6,
  },
}
