export const MONSTERS = {
  rat: {
    key: 'rat',
    name: 'Rat',
    move: 5,
    attack: 1,
    accuracy: 0.5,
    defense: 0,
    deflection: 0.166,
    body: 1,
    mind: 1,
  },
  kobold: {
    key: 'kobold',
    name: 'Kobold',
    move: 9,
    attack: 1,
    accuracy: 0.5,
    defense: 1,
    deflection: 0.166,
    body: 1,
    mind: 1,
  },
  goblin: {
    key: 'goblin',
    name: 'Goblin',
    move: 10,
    attack: 2,
    accuracy: 0.5,
    defense: 1,
    deflection: 0.166,
    body: 1,
    mind: 1,
  },
  skeleton: {
    key: 'skeleton',
    name: 'Skeleton',
    move: 6,
    attack: 2,
    accuracy: 0.5,
    defense: 2,
    deflection: 0.166,
    body: 1,
    mind: 0,
  },
  mummy: {
    key: 'mummy',
    name: 'Mummy',
    move: 4,
    attack: 3,
    accuracy: 0.5,
    defense: 4,
    deflection: 0.166,
    body: 2,
    mind: 0,
  },
  orc: {
    key: 'orc',
    name: 'Orc',
    move: 8,
    attack: 3,
    accuracy: 0.5,
    defense: 2,
    deflection: 0.166,
    body: 2,
    mind: 2,
  },
  zombie: {
    key: 'zombie',
    name: 'Zombie',
    move: 4,
    attack: 2,
    accuracy: 0.5,
    defense: 3,
    deflection: 0.166,
    body: 2,
    mind: 0,
  },
  fimir: {
    key: 'fimir',
    name: 'Fimir',
    move: 6,
    attack: 3,
    accuracy: 0.5,
    defense: 3,
    deflection: 0.166,
    body: 3,
    mind: 3,
  },
  chaos_warrior: {
    key: 'chaos_warrior',
    name: 'Choes Warrior',
    move: 6,
    attack: 3,
    accuracy: 0.5,
    defense: 4,
    deflection: 0.166,
    body: 3,
    mind: 3,
  },
  gargoyle: {
    key: 'gargoyle',
    name: 'Gargoyle',
    move: 6,
    attack: 4,
    accuracy: 0.5,
    defense: 4,
    deflection: 0.166,
    body: 4,
    mind: 4,
  },
};
