export const MONSTERS = {
  rat: {
    key: 'rat',
    name: 'Rat',
    move: 5,
    attack: 1,
    defend: 0,
    health: 1,
    sanity: 1,
  },
  kobold: {
    key: 'kobold',
    name: 'Kobold',
    move: 9,
    attack: 1,
    defend: 1,
    health: 1,
    sanity: 1,
  },
  goblin: {
    key: 'goblin',
    name: 'Goblin',
    move: 10,
    attack: 2,
    defend: 1,
    health: 1,
    sanity: 1,
  },
  mummy: {
    key: 'mummy',
    name: 'Mummy',
    move: 4,
    attack: 3,
    defend: 4,
    health: 1,
    sanity: 0,
  },
  orc: {
    key: 'orc',
    name: 'Orc',
    move: 8,
    attack: 3,
    defend: 2,
    health: 1,
    sanity: 2,
  },
  skeleton: {
    key: 'skeleton',
    name: 'Skeleton',
    move: 6,
    attack: 2,
    defend: 2,
    health: 1,
    sanity: 0,
  },
  zombie: {
    key: 'zombie',
    name: 'Zombie',
    move: 4,
    attack: 2,
    defend: 3,
    health: 1,
    sanity: 0,
  },
  fimir: {
    key: 'fimir',
    name: 'Fimir',
    move: 6,
    attack: 3,
    defend: 3,
    health: 1,
    sanity: 3,
  },
  chaos_warrior: {
    key: 'chaos_warrior',
    name: 'Choes Warrior',
    move: 6,
    attack: 3,
    defend: 4,
    health: 1,
    sanity: 3,
  },
  gargoyle: {
    key: 'gargoyle',
    name: 'Gargoyle',
    move: 6,
    attack: 4,
    defend: 4,
    health: 1,
    sanity: 4,
  },
};
